### ISSUE TITLE
Bug in battle series

### ISSUE THREAD

**Issue by andrew-fleming** [dustinstacy/triple-triad-reactjs#116]
For both five and seven game series, winning 3 and 4 games respectively doesn't trigger a win and the series continues.

**Comment by dustinstacy** [comment]
Due to winning parameters and scoring changes, we now have to determine if the series is terminated upon an insurmountable lead being achieved. Going to leave this open while testing is ongoing to confirm the results.

**Comment by dustinstacy** [comment]
Oops, or not.

**Comment by dustinstacy** [comment]
Looks to be all good, probably worth creating a function test to ensure there's no edge cases.

**Comment by andrew-fleming** [comment]
> probably worth creating a function test to ensure there's no edge cases.

+1
