### ISSUE TITLE
Bug: disappearing card

### ISSUE THREAD

**Issue by andrew-fleming** [dustinstacy/triple-triad-reactjs#123]
When placing down a card during the opponent's turn, the card disappears and can no longer be used during the game.

**Comment by dustinstacy** [comment]
Great catch! Makes sense given there were safeguards in place for the onClick selection, however there were none implemented for the drag and drop functionality.

To clarify the accuracy of that statement, this occurs only when trying to drag the card or during the click and select mode as well?

**Comment by andrew-fleming** [comment]
Ah right, I should have clarified. Only during drag and drop

**Comment by dustinstacy** [comment]
Got it! Seems to be in working as intended now.
