### ISSUE TITLE
Feature: premoves

### ISSUE THREAD

**Issue by andrew-fleming** [dustinstacy/triple-triad-reactjs#124]
During the opponent's turn, it'd be convenient to preemptively set a card on a square. The card will automatically be placed after the opponent's turn. If the opponent sets a card on the same square first, the action is cancelled.

Premoves are great in chess and help speed up the game.

**Comment by dustinstacy** [comment]
Two immediate thoughts I have for this potential feature.

1. It's value is apparent in chess as its a 64 square, 32 piece game if I'm not mistaken. In a game with only 9 squares and a quick pace to begin with, it may not provide as much benefit.
2. However, nothing beats actually testing the idea and I would venture to believe that it wouldn't be a challenge at all to implement. I'd consider it a 'mid-road' feature tied to a couple of other quality of life improvements on the way. Thanks for the idea, keep 'em coming!

**Comment by andrew-fleming** [comment]
1. True, it's much more beneficial in chess (specifically for blitz games) because of the timer and the number of options. I think this could be helpful in Nexus when new rules are added which require calculation as well as the introduction of timer
2. Agreed on testing the idea and it being a "mid-road" feature

**Comment by dustinstacy** [comment]
Ported to new repo roadmap
