### ISSUE TITLE
Normalize card values

### ISSUE THREAD

**Issue by andrew-fleming** [dustinstacy/triple-triad-reactjs#140]
When logging the "battling" card values, it seems they're a mix of strings and integers. I'm guessing the cpu's vals are ints and the player's vals are strings?
![Screen Shot 2023-06-22 at 3 11 13 AM](https://github.com/dustinstacy/triple-triad-reactjs/assets/69282788/036a06fc-9cf9-479d-bd55-d5d258c82b21)

**Comment by dustinstacy** [comment]
Good Catch!
