### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by dustinstacy** [dustinstacy/triple-triad-reactjs#39]
- [x] Last card placement does not execute during some matches. May be due to when empty cell is being checked.
- [x] Pack count is not deducting on use until refresh or navigation occurs. Need a render update.
- [x] Score is not updating on final move to accurately represent winner. Need a final render update before `checkForWin()`
- [x] During match set up screen (current.replace is not a function). This has to do to the cards.values being inaccessible as the cards themselves have failed to populate. _Seems to only be occurring after a game is played with the elements rule_
- [x] During match score and/or backgrounds for each player will not be accurate. It appears the `card.user` is inaccurate in some scenarios and may be due to previous outcomes from other matches not resetting.
- [x] When Boosted by element 'A' becomes NaN
- [x] When AI checks all possible moves using `checkElements()` cards remain boosted even if they are not played

**Comment by andrew-fleming** [comment]
This is all done, no? Close the issue!

**Comment by dustinstacy** [comment]
Had this up as a catch all for any bugs that were found, but yes, at this stage let's get it out of here!
