### ISSUE TITLE
Fix layout in deck screen

### ISSUE THREAD

**Issue by andrew-fleming** [dustinstacy/triple-triad-reactjs#69]
The elemental icons extend beyond the screen and the `Cards in Deck` is bleeding into the border a bit.

![Screen Shot 2023-03-21 at 11 03 40 AM](https://user-images.githubusercontent.com/69282788/226650805-63d57aca-e094-4417-b542-9a2d94755edc.png)

**Comment by dustinstacy** [comment]
Good catch! I am actually going to close this out though, only because this and a handful of other things fall under the umbrella of responsive design. For clarity though, I am renaming #42 to "Responsive design" to encompass these necessary fixes.
